### ISSUE TITLE
Репозиторий — это корень папки

### ISSUE THREAD

**Issue by phoenixweiss** [Kuistal9/Homework_1#5]
Если весь твой проект — это всего одна папка, то не нужно ее закидывать в репозиторий. Репозиторий — это и есть корень папки проекта.

ПЛОХО:

```
Homework_1/
    |
    homework/
        |
        index.html
        script.js
```

ХОРОШО:

```
Homework_1/
    |
    index.html
    script.js
```

**Comment by Kuistal9** [comment]
Папка в паке с папкой в папке

**Comment by Kuistal9** [comment]
Изминил структуру
