### ISSUE TITLE
Облегчение 


### ISSUE THREAD

**Issue by Kuistal9** [Kuistal9/Homework_1#6]
Изменил конструкцию 
(If
Else if
Else)
 
if (n2==n4,n1==n3)  
  { 
     alert( 'Счёт и результат были угаданы верно !!' ); 
    }   
 else if (score_real==score_expected) 
 { 
   alert( 'Счёт не угадали,!' ) 
     alert( 'результат был угадан верно!!' ); 
 } 
 else 
 {  
   alert( 'Счёт не угадали, результат не был угадан!' ) 
    
 }

**Comment by phoenixweiss** [comment]
Почитай про markdown в гитхабе, и как оформляется код в комментариях...

🤦‍♂️
